#!/bin/bash
# grub-sign
# Signs everything important in /boot. Depends on grub2-verify.
# Author: Praden Florian based on Bandie Kojote
# Licence: GNU-GPLv3

# Script basic conf
SDIR="/usr/local/sbin"
CFGDIR="/etc/grub-sign"

# Source env variable
if [[ -e "${CFGDIR}/env" ]]; then
    source "${CFGDIR}/env"
else
    source "${CFGDIR}/default.env"
fi;

# sourcing common function
source "${SDIR}/grub-sign-common.sh"

# Running grub-verify first to prevent double signing
e_header "Running grub-verify to check if everything is unsigned..."
# Run grub-verify in quiet mode
"${SDIR}/grub-verify" 1
case "$?" in
    1|3)
        e_note "Some sig are missing or in error. You could use grub-sign-update for updating faster."
        ;;
    2)
        e_note "Full signing from unsigned grub directory."
        ;;
    0)
        e_note "Nothing to do, all file are signed and verified."
        if [[ "$1" == "--force" ]]; then
            e_warning "Forcing resign"
        else
            e_note "Exiting. Use --force to force a full resign."
            exit 0;
        fi;
        ;;
    *)
        e_error "Unknown error. Full resign."
        ;;
esac

e_header "Signing files"
# Find GRUB2 datas
list-all-files
e_arrow "${yellow}${bold}${#FILES[@]}${reset} files to sign"
for F in "${FILES[@]}"; do 
    # Signing
    echo -n " +++ ${F} "
    sign-file "${F}"
done
e_header "Done!"
exit 0;
