#!/bin/bash
# grub-verify
# Checks the signatures of every file which is has a signature in boot dir.
# Author: Praden Florian based on Bandie Kojote
# Licence: GNU-GPLv3

quiet="$1"

# Script basic conf
SDIR="/usr/local/sbin"
CFGDIR="/etc/grub-sign"

# Source env variable
if [[ -e "${CFGDIR}/env" ]]; then
    source "${CFGDIR}/env"
else
    source "${CFGDIR}/default.env"
fi;

# sourcing common function
source "${SDIR}/grub-sign-common.sh"

sig_files=( )
error_files=( )
missing_files=( )

e_header "Checking signatures in \"${BOOTDIR}\"..."
list-all-files
e_arrow "${yellow}${bold}${#FILES[@]}${reset} files to test"
for F in "${FILES[@]}"; do
    if [[ "x${quiet}" != "x1" ]]; then
        echo -n " + ${F} "
    fi;
    verif-file "$F" ${quiet}
    case "$?" in
        3)
            # Missing sig
            missing_files+=( "${F}" )
            ;;
        0)
            # Sig correct
            sig_files+=( "${F}" )
            ;;
        *)
            # Error happen
            error_files+=( "${F}" )
            ;;
    esac
done
# Nothing to verify? Exit 2.
if [[ (${#sig_files[@]} == 0) && (${#error_files[@]} == 0) ]]; then
    e_arrow "Nothing to verify."
    exit 2
fi

# Message signatures
if (( ${#error_files} == 0 )); then
    e_success "Found no bad signature."
else
    e_error "Found ${#error_files[@]} bad signatures"
fi

# Message missing
if (( ${#missing_files} == 0 )); then
    e_success "Found no missing signatures."
else
    e_warning "Found ${#missing_files[@]} missing signatures."
fi

e_note "${#sig_files[@]} correct signatures"

# File list
if (( ${#error_files[@]} > 0 )); then
    echo "BAD signature: ${error_files[@]}"
fi

if (( ${#missing_files[@]} > 0 )); then
    echo "MISSING signatures: ${missing_files[@]}"
fi

# Exit codes
if (( ${#error_files[@]} > 0 )); then
    exit 1
fi

if (( ${#missing_files[@]} > 0 )); then
    exit 3
fi

exit 0
