#!/bin/bash
# grub-sign
# Signs everything important in /boot. Depends on grub2-verify.
# Author: Praden Florian based on Bandie Kojote
# Licence: GNU-GPLv3

# Script basic conf
SDIR="/usr/local/sbin"
CFGDIR="/etc/grub-sign"

# Source env variable
if [[ -e "${CFGDIR}/env" ]]; then
    source "${CFGDIR}/env"
else
    source "${CFGDIR}/default.env"
fi;

# sourcing common function
source "${SDIR}/grub-sign-common.sh"

# Running grub-verify first to prevent double signing
e_header "Running grub-verify to check if everything is unsigned..."
"${SDIR}/grub-verify"
if [ $? -lt 2 ]
then
    e_error "Run grub-unsign first."
    exit 1
fi

e_header "Signing files"
# Find GRUB2 datas
list-all-files
e_arrow "${yellow}${bold}${#FILES[@]}${reset} files to sign"
for F in "${FILES[@]}"; do 
    # Signing
    echo -n " +++ ${F} "
    sign-file "${F}"
done
e_header "Done!"
exit 0
