#!/bin/bash
# grub-unsign
# Unsigns every file in /boot. Depends on grub2-verify
# Author: Praden Florian based on Bandie Kojote
# Licence: GNU-GPLv3

# Script basic conf
SDIR="/usr/local/sbin"
CFGDIR="/etc/grub-sign"

# Source env variable
if [[ -e "${CFGDIR}/env" ]]; then
    source "${CFGDIR}/env"
else
    source "${CFGDIR}/default.env"
fi;

# sourcing common function
source "${SDIR}/grub-sign-common.sh"

quiet="$1"
if [[ "x${quiet}" == "x" ]]; then
    # By default quiet
    quiet=1
fi;

# Check if something is wrong
# Run grub-verify
"${SDIR}/grub-verify" "$quiet"
stat="$?"
case "${stat}" in
1)
    e_warning "grub-verify has detected a one or more bad signatures."
    e_warning "Please check for malicious software before you're unsigning everything!"
  exit 1
	;;
2)
  e_note "Everything is unsigned already."
  exit 0
	;;
3)
  e_note "Ignoring missing signatures..."
	;&
0|3)	
  # Then remove the signatures.
  find "${BOOTDIR}" -name '*.sig' -delete

  e_success "GRUB2 unsigned."
  e_warning "WARNING: If you want to deactivate GRUB2's signature feature, change the check_signatures variable in the grub config file!"
  exit 0
	;;
*)
  e_error "Something unknown happened!"
  exit ${stat}
esac
