#!/bin/bash
# grub-sign
# Signs everything important in /boot. Depends on grub2-verify.
# Author: Praden Florian based on Bandie Kojote
# Licence: GNU-GPLv3

# Script basic conf
SDIR="/usr/local/sbin"
CFGDIR="/etc/grub-sign"

# Source env variable
if [[ -e "${CFGDIR}/env" ]]; then
    source "${CFGDIR}/env"
else
    source "${CFGDIR}/default.env"
done;




# Running grub-verify first to prevent double signing
echo "Running grub-verify to check if everything is unsigned..."
"${SDIR}/grub-verify"
if [ $? -lt 2 ]
then
    echo "Run grub-unsign first."
    exit 1
fi

echo "==== Signing files ===="
# Find GRUB2 datas
for i in $(find "${BOOTDIR}" -name "*.cfg" -or -name "*.lst" -or \
 -name "*.mod" -or -name "vmlinuz*" -or -name "initrd*" -or \
 -name "grubenv" -or -name "*.asc" -or -name "*.pf2" -or \
 -name "*.efi" -or -name "*.elf" -or -name "*.bin" -or \
 -name "*-generic" -or -name "*.jpg" -or -name "*.png" -or -name "*.mo");
do
    # Signing
    echo " +++ ${i}"
    gpg --homedir "${GPGDIR}" ${GPGARGS} --batch --detach-sign --no-tty "${i}"
    if [ $? -eq 0 ]
    then
        echo " ++++++ signed ++++++"
    else
        echo " ****** ERROR! ******"
	      break
    fi
done


echo "====== Done! ====="
exit 0
